### ISSUE TITLE
Set minimal version to augeas

### ISSUE THREAD

**Issue by camlafit** [abbat/letsencrypt.pkg#1]
As apache module use augeas lib, should bu interesting to recommend or force at least 1.2 version.
On wheezy these lib are presents in backports

 `The error was: NotSupportedError('Apache plugin support requires libaugeas0 and augeas-lenses version 1.2.0 or higher, please make sure you have you have those installed.',)`

**Comment by abbat** [comment]
Should be fixed now. If backports enabled in sources.list, augeas-lenses from backports will be used and from OBS otherwise.

**Comment by camlafit** [comment]
Thanks :)
